version: '3.1'
services:
  aboo-vite-frontend:
    image: registry.gitlab.com/aboo9442027/frontend/aboo-vite-frontend:latest
    build:
      dockerfile: Dockerfile-prod
    container_name: aboo-vite-frontend
    ports:
      - '31311:80'
