version: '3.1'
services:
  vite:
    image: registry.gitlab.com/aboo9442027/frontend/vite:latest
    build:
      dockerfile: Dockerfile-prod
    container_name: aboo-fronend-prod
    ports:
      - '31311:80'
